### ISSUE TITLE
There are four errors in the first running code of the configuration planner in the example.

### ISSUE THREAD

**Issue by zcc0514** [ethz-asl/mav_active_3d_planning#62]
Hello!
First of all, thank you very much for your wonderful work! I have completed the installation process described in your README.md, and I can also successfully download experimental scenes, ground truth point clouds and other related resources. However, in the following example-configuring Planner, there was a problem when running "roslaunch active_3d_planning_app_reconstruction example.launch", and four errors were generated. The following is the result after I entered this line of command, and I will send you a separate screenshot of the error report. I would be very grateful if you could answer it for me. Looking forward to your reply!

... logging to /home/dlvirmac/.ros/log/d4b84872-b13e-11ee-9e6e-525400d9ad51/roslaunch-dlvirmac-Standard-PC-i440FX-PIIX-1996-27030.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dlvirmac-Standard-PC-i440FX-PIIX-1996:36105/

SUMMARY
========

CLEAR PARAMETERS
 * /firefly/PID_attitude_controller/
 * /firefly/mav_nonlinear_mpc/

PARAMETERS
 * /firefly/PID_attitude_controller/allocation_matrix: [0.5, -0.866025, ...
 * /firefly/PID_attitude_controller/arm_length: 0.2156
 * /firefly/PID_attitude_controller/inertia: [0.034756, 0.0, 0...
 * /firefly/PID_attitude_controller/max_integrator_error: 0.6
 * /firefly/PID_attitude_controller/n_rotors: 6
 * /firefly/PID_attitude_controller/p_gain: 25
 * /firefly/PID_attitude_controller/pitch_gain: 70
 * /firefly/PID_attitude_controller/pitch_int_gain: 2.0
 * /firefly/PID_attitude_controller/q_gain: 22
 * /firefly/PID_attitude_controller/r_gain: 1.0
 * /firefly/PID_attitude_controller/roll_gain: 70
 * /firefly/PID_attitude_controller/roll_int_gain: 2.0
 * /firefly/PID_attitude_controller/rotor_force_constant: 8.54858e-06
 * /firefly/PID_attitude_controller/rotor_moment_constant: 0.016
 * /firefly/mav_nonlinear_mpc/KF_observer/P0_angular_velocity: 0.1
 * /firefly/mav_nonlinear_mpc/KF_observer/P0_attitude: 0.1
 * /firefly/mav_nonlinear_mpc/KF_observer/P0_force: 0.1
 * /firefly/mav_nonlinear_mpc/KF_observer/P0_position: 0.1
 * /firefly/mav_nonlinear_mpc/KF_observer/P0_torque: 0.1
 * /firefly/mav_nonlinear_mpc/KF_observer/P0_velocity: 0.1
 * /firefly/mav_nonlinear_mpc/KF_observer/calibration_duration: 5
 * /firefly/mav_nonlinear_mpc/KF_observer/drag_coefficients: [0.01, 0.01, 0]
 * /firefly/mav_nonlinear_mpc/KF_observer/external_forces_limit: [5.0, 5.0, 3.0]
 * /firefly/mav_nonlinear_mpc/KF_observer/external_moments_limit: [20.0, 20.0, 20.0]
 * /firefly/mav_nonlinear_mpc/KF_observer/omega_limit: [3.0, 3.0, 2.0]
 * /firefly/mav_nonlinear_mpc/KF_observer/pitch_damping: 0.76
 * /firefly/mav_nonlinear_mpc/KF_observer/pitch_gain: 0.84
 * /firefly/mav_nonlinear_mpc/KF_observer/pitch_omega: 7.07
 * /firefly/mav_nonlinear_mpc/KF_observer/q_angular_velocity: 0.02
 * /firefly/mav_nonlinear_mpc/KF_observer/q_attitude: 0.015
 * /firefly/mav_nonlinear_mpc/KF_observer/q_force: 0.1
 * /firefly/mav_nonlinear_mpc/KF_observer/q_position: 0.01
 * /firefly/mav_nonlinear_mpc/KF_observer/q_torque: 0.1
 * /firefly/mav_nonlinear_mpc/KF_observer/q_velocity: 0.025
 * /firefly/mav_nonlinear_mpc/KF_observer/r_attitude: 0.01
 * /firefly/mav_nonlinear_mpc/KF_observer/r_position: 0.001
 * /firefly/mav_nonlinear_mpc/KF_observer/r_velocity: 0.0012
 * /firefly/mav_nonlinear_mpc/KF_observer/roll_damping: 0.72
 * /firefly/mav_nonlinear_mpc/KF_observer/roll_gain: 0.8
 * /firefly/mav_nonlinear_mpc/KF_observer/roll_omega: 7.07
 * /firefly/mav_nonlinear_mpc/KF_observer/yaw_damping: 0.95
 * /firefly/mav_nonlinear_mpc/KF_observer/yaw_gain: 1.0
 * /firefly/mav_nonlinear_mpc/KF_observer/yaw_omega: 5.0
 * /firefly/mav_nonlinear_mpc/K_yaw: 1.8
 * /firefly/mav_nonlinear_mpc/Ki_xy: 0.2
 * /firefly/mav_nonlinear_mpc/Ki_z: 0.3
 * /firefly/mav_nonlinear_mpc/antiwindup_ball: 0.4
 * /firefly/mav_nonlinear_mpc/enable_integrator: True
 * /firefly/mav_nonlinear_mpc/enable_offset_free: True
 * /firefly/mav_nonlinear_mpc/linear_drag_coefficients: [0.01, 0.01, 0]
 * /firefly/mav_nonlinear_mpc/mass: 1.56
 * /firefly/mav_nonlinear_mpc/pitch_gain: 0.78
 * /firefly/mav_nonlinear_mpc/pitch_max: 0.436332312999
 * /firefly/mav_nonlinear_mpc/pitch_time_constant: 0.259
 * /firefly/mav_nonlinear_mpc/position_error_integration_limit: 2
 * /firefly/mav_nonlinear_mpc/prediction_sampling_time: 0.1
 * /firefly/mav_nonlinear_mpc/q_pitch: 10
 * /firefly/mav_nonlinear_mpc/q_roll: 10
 * /firefly/mav_nonlinear_mpc/q_vx: 80
 * /firefly/mav_nonlinear_mpc/q_vy: 80
 * /firefly/mav_nonlinear_mpc/q_vz: 100
 * /firefly/mav_nonlinear_mpc/q_x: 80
 * /firefly/mav_nonlinear_mpc/q_y: 80
 * /firefly/mav_nonlinear_mpc/q_z: 120
 * /firefly/mav_nonlinear_mpc/r_pitch: 50
 * /firefly/mav_nonlinear_mpc/r_roll: 50
 * /firefly/mav_nonlinear_mpc/r_thrust: 1
 * /firefly/mav_nonlinear_mpc/reference_frame: world
 * /firefly/mav_nonlinear_mpc/roll_gain: 0.75
 * /firefly/mav_nonlinear_mpc/roll_max: 0.436332312999
 * /firefly/mav_nonlinear_mpc/roll_time_constant: 0.257
 * /firefly/mav_nonlinear_mpc/sampling_time: 0.0021
 * /firefly/mav_nonlinear_mpc/thrust_max: 20
 * /firefly/mav_nonlinear_mpc/thrust_min: 5
 * /firefly/mav_nonlinear_mpc/use_rc_teleop: False
 * /firefly/mav_nonlinear_mpc/verbose: False
 * /firefly/odometry_noise_model/noise_model: random_walk
 * /firefly/odometry_noise_model/position_uncertainty: 0.05
 * /firefly/odometry_noise_model/publish_tf: True
 * /firefly/odometry_noise_model/roll_pitch_uncertainty: 1.5
 * /firefly/odometry_noise_model/yaw_uncertainty: 5.0
 * /firefly/robot_description: <?xml version="1....
 * /firefly/tf_prefix: 
 * /gazebo/enable_ros_network: True
 * /map_bounding_volume/x_max: 30.0
 * /map_bounding_volume/x_min: -10.0
 * /map_bounding_volume/y_max: 18.0
 * /map_bounding_volume/y_min: -22.0
 * /map_bounding_volume/z_max: 13.5
 * /map_bounding_volume/z_min: -1.5
 * /planner/planner_node/back_tracker/n_rotations: 1
 * /planner/planner_node/back_tracker/sampling_rate: 20.0
 * /planner/planner_node/back_tracker/stack_size: 10
 * /planner/planner_node/back_tracker/turn_rate: 1.6
 * /planner/planner_node/back_tracker/type: RotateReverse
 * /planner/planner_node/back_tracker/update_rate: 2.0
 * /planner/planner_node/build_modules_on_init: True
 * /planner/planner_node/highlight_executed_trajectory: True
 * /planner/planner_node/map/type: VoxbloxMap
 * /planner/planner_node/max_new_segments: 0
 * /planner/planner_node/max_new_tries: 0
 * /planner/planner_node/min_new_segments: 0
 * /planner/planner_node/min_new_tries: 0
 * /planner/planner_node/min_new_value: 0
 * /planner/planner_node/publish_pointclouds: False
 * /planner/planner_node/publish_traversable: False
 * /planner/planner_node/replan_pos_threshold: 0.25
 * /planner/planner_node/replan_yaw_threshold: 0.15
 * /planner/planner_node/system_constraints/a_max: 1.0
 * /planner/planner_node/system_constraints/collision_radius: 0.7
 * /planner/planner_node/system_constraints/v_max: 1.0
 * /planner/planner_node/system_constraints/yaw_accel_max: 1.6
 * /planner/planner_node/system_constraints/yaw_rate_max: 1.6
 * /planner/planner_node/trajectory_evaluator/bounding_volume_args: /target_bounding_...
 * /planner/planner_node/trajectory_evaluator/camera_params_ns: /unreal/unreal_ro...
 * /planner/planner_node/trajectory_evaluator/clear_from_parents: False
 * /planner/planner_node/trajectory_evaluator/cost_computer/type: SegmentTime
 * /planner/planner_node/trajectory_evaluator/evaluator_updater/type: UpdateAll
 * /planner/planner_node/trajectory_evaluator/evaluator_updater/update_cost: False
 * /planner/planner_node/trajectory_evaluator/evaluator_updater/update_gain: False
 * /planner/planner_node/trajectory_evaluator/evaluator_updater/update_value: True
 * /planner/planner_node/trajectory_evaluator/next_selector/type: SubsequentBest
 * /planner/planner_node/trajectory_evaluator/sensor_model/downsampling_factor: 3.0
 * /planner/planner_node/trajectory_evaluator/sensor_model/focal_length: 320.0
 * /planner/planner_node/trajectory_evaluator/sensor_model/ray_length: 5.0
 * /planner/planner_node/trajectory_evaluator/sensor_model/resolution_x: 640
 * /planner/planner_node/trajectory_evaluator/sensor_model/resolution_y: 480
 * /planner/planner_node/trajectory_evaluator/sensor_model/sampling_time: 0.0
 * /planner/planner_node/trajectory_evaluator/sensor_model/type: IterativeRayCaster
 * /planner/planner_node/trajectory_evaluator/type: NaiveEvaluator
 * /planner/planner_node/trajectory_evaluator/value_computer/following_value_computer/cost_weight: 1.0
 * /planner/planner_node/trajectory_evaluator/value_computer/following_value_computer/gain_weight: 0.1
 * /planner/planner_node/trajectory_evaluator/value_computer/following_value_computer/type: LinearValue
 * /planner/planner_node/trajectory_evaluator/value_computer/type: AccumulateValue
 * /planner/planner_node/trajectory_evaluator/visualize_sensor_view: True
 * /planner/planner_node/trajectory_generator/ascent_angle: 0.523
 * /planner/planner_node/trajectory_generator/bounding_volume_args: /map_bounding_volume
 * /planner/planner_node/trajectory_generator/collision_optimistic: False
 * /planner/planner_node/trajectory_generator/distance: 1.5
 * /planner/planner_node/trajectory_generator/generator_updater/type: RecheckCollision
 * /planner/planner_node/trajectory_generator/n_segments: 5
 * /planner/planner_node/trajectory_generator/sampling_rate: 20
 * /planner/planner_node/trajectory_generator/segment_selector/factor: 2.0
 * /planner/planner_node/trajectory_generator/segment_selector/leaf_probability: 1.0
 * /planner/planner_node/trajectory_generator/segment_selector/revisit: False
 * /planner/planner_node/trajectory_generator/segment_selector/type: RandomWeighted
 * /planner/planner_node/trajectory_generator/segment_selector/uniform_probability: 0.2
 * /planner/planner_node/trajectory_generator/type: Uniform
 * /planner/planner_node/trajectory_generator/yaw_angle: 1.2
 * /planner/planner_node/tsdf_voxel_size: 0.1
 * /planner/planner_node/tsdf_voxels_per_side: 16
 * /planner/planner_node/update_mesh_every_n_sec: 0.0
 * /planner/planner_node/use_tf_transforms: False
 * /planner/planner_node/verbose: True
 * /planner/planner_node/verbose_modules: True
 * /planner/planner_node/visualize: True
 * /planner/system_constraints/a_max: 1.0
 * /planner/system_constraints/v_max: 1.0
 * /planner/system_constraints/yaw_rate_max: 1.57
 * /planner/voxblox_node/allow_clear: True
 * /planner/voxblox_node/color_mode: color
 * /planner/voxblox_node/max_ray_length: 5.0
 * /planner/voxblox_node/method: merged
 * /planner/voxblox_node/publish_esdf_map: True
 * /planner/voxblox_node/publish_tsdf_map: True
 * /planner/voxblox_node/tsdf_voxel_size: 0.1
 * /planner/voxblox_node/tsdf_voxels_per_side: 16
 * /planner/voxblox_node/update_mesh_every_n_sec: 1.0
 * /planner/voxblox_node/use_tf_transforms: True
 * /planner/voxblox_node/verbose: False
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /target_bounding_volume/x_max: 20
 * /target_bounding_volume/x_min: 0
 * /target_bounding_volume/y_max: 8
 * /target_bounding_volume/y_min: -12
 * /target_bounding_volume/z_max: 10
 * /target_bounding_volume/z_min: -1.5
 * /unreal/eval_data_node/delay: 3.0
 * /unreal/eval_data_node/evaluate: False
 * /unreal/eval_data_node/ns_planner: /planner/planner_...
 * /unreal/eval_data_node/ns_voxblox: /planner/voxblox_...
 * /unreal/eval_data_node/startup_timeout: 30.0
 * /unreal/simulation_manager/horizon: 20
 * /unreal/simulation_manager/monitor: True
 * /unreal/simulation_manager/ns_gazebo: /gazebo
 * /unreal/simulation_manager/ns_mav: /firefly
 * /unreal/unreal_ros_client/collision_on: True
 * /unreal/unreal_ros_client/mode: fast
 * /unreal/unreal_ros_client/publish_tf: False
 * /unreal/unreal_ros_client/slowdown: 0.0
 * /unreal/unreal_sensor_model/camera_params_ns: /unreal/unreal_ro...
 * /unreal/unreal_sensor_model/flatten_distance: 6.0
 * /unreal/unreal_sensor_model/k_mu_2: 0.0024
 * /unreal/unreal_sensor_model/k_sigma_2: 0.0024
 * /unreal/unreal_sensor_model/maximum_distance: 0.0
 * /unreal/unreal_sensor_model/model_type: gaussian_depth_noise
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    rviz_voxblox (rviz/rviz)
  /firefly/
    PID_attitude_controller (mav_lowlevel_attitude_controller/mav_pid_attitude_controller_node)
    mav_nonlinear_mpc (mav_nonlinear_mpc/nonlinear_mpc_node)
    odometry_noise_model (active_3d_planning_app_reconstruction/gps_odometry_simulator.py)
    spawn_firefly (gazebo_ros/spawn_model)
    tf_camera_to_link (tf/static_transform_publisher)
  /planner/
    planner_node (active_3d_planning_app_reconstruction/reconstruction_planner_node)
    voxblox_node (voxblox_ros/esdf_server)
  /unreal/
    eval_data_node (active_3d_planning_app_reconstruction/eval_data_node.py)
    simulation_manager (unreal_cv_ros/simulation_manager.py)
    unreal_ros_client (unreal_cv_ros/unreal_ros_client.py)
    unreal_sensor_model (unreal_cv_ros/sensor_model.py)

auto-starting new master
process[master]: started with pid [27050]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d4b84872-b13e-11ee-9e6e-525400d9ad51
process[rosout-1]: started with pid [27069]
started core service [/rosout]
process[gazebo-2]: started with pid [27077]
process[firefly/spawn_firefly-3]: started with pid [27081]
ERROR: cannot launch node of type [mav_nonlinear_mpc/nonlinear_mpc_node]: Cannot locate node of type [nonlinear_mpc_node] in package [mav_nonlinear_mpc]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [mav_lowlevel_attitude_controller/mav_pid_attitude_controller_node]: Cannot locate node of type [mav_pid_attitude_controller_node] in package [mav_lowlevel_attitude_controller]. Make sure file exists in package path and permission is set to executable (chmod +x)
process[firefly/odometry_noise_model-6]: started with pid [27083]
process[firefly/tf_camera_to_link-7]: started with pid [27084]
process[unreal/unreal_ros_client-8]: started with pid [27086]
process[unreal/unreal_sensor_model-9]: started with pid [27092]
process[unreal/simulation_manager-10]: started with pid [27093]
process[unreal/eval_data_node-11]: started with pid [27101]
ERROR: cannot launch node of type [voxblox_ros/esdf_server]: Cannot locate node of type [esdf_server] in package [voxblox_ros]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [active_3d_planning_app_reconstruction/reconstruction_planner_node]: Cannot locate node of type [reconstruction_planner_node] in package [active_3d_planning_app_reconstruction]. Make sure file exists in package path and permission is set to executable (chmod +x)
=> Info: Use inet client...
process[rviz_voxblox-14]: started with pid [27102]
Traceback (most recent call last):
  File "/home/dlvirmac/catkin_ws/src/mav_active_3d_planning/active_3d_planning_app_reconstruction/src/experiments/gps_odometry_simulator.py", line 10, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
Traceback (most recent call last):
  File "/home/dlvirmac/catkin_ws/src/unreal_cv_ros/unreal_cv_ros/src/sensor_model.py", line 4, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
Traceback (most recent call last):
  File "/home/dlvirmac/catkin_ws/src/mav_active_3d_planning/active_3d_planning_app_reconstruction/src/experiments/eval_data_node.py", line 13, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
Traceback (most recent call last):
  File "/home/dlvirmac/catkin_ws/src/unreal_cv_ros/unreal_cv_ros/src/unreal_ros_client.py", line 7, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
[firefly/odometry_noise_model-6] process has died [pid 27083, exit code 1, cmd /home/dlvirmac/catkin_ws/src/mav_active_3d_planning/active_3d_planning_app_reconstruction/src/experiments/gps_odometry_simulator.py odometry_in:=ground_truth/odometry __name:=odometry_noise_model __log:=/home/dlvirmac/.ros/log/d4b84872-b13e-11ee-9e6e-525400d9ad51/firefly-odometry_noise_model-6.log].
log file: /home/dlvirmac/.ros/log/d4b84872-b13e-11ee-9e6e-525400d9ad51/firefly-odometry_noise_model-6*.log
Traceback (most recent call last):
  File "/home/dlvirmac/catkin_ws/src/unreal_cv_ros/unreal_cv_ros/src/simulation_manager.py", line 4, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
================================================================================REQUIRED process [unreal/unreal_ros_client-8] has died!
process has died [pid 27086, exit code 1, cmd /home/dlvirmac/catkin_ws/src/unreal_cv_ros/unreal_cv_ros/src/unreal_ros_client.py odometry:=/firefly/ground_truth/odometry __name:=unreal_ros_client __log:=/home/dlvirmac/.ros/log/d4b84872-b13e-11ee-9e6e-525400d9ad51/unreal-unreal_ros_client-8.log].
log file: /home/dlvirmac/.ros/log/d4b84872-b13e-11ee-9e6e-525400d9ad51/unreal-unreal_ros_client-8*.log
Initiating shutdown!
================================================================================
[rviz_voxblox-14] killing on exit
[unreal/eval_data_node-11] killing on exit
[unreal/simulation_manager-10] killing on exit
[unreal/unreal_sensor_model-9] killing on exit
[unreal/unreal_ros_client-8] killing on exit
[firefly/tf_camera_to_link-7] killing on exit
[firefly/spawn_firefly-3] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 34, in <module>
    from tf.transformations import quaternion_from_euler
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 39, in <module>
    from .buffer_interface import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/buffer_interface.py", line 32, in <module>
    import roslib; roslib.load_manifest('tf2_ros')
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 64, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 97, in _generate_python_path
    m = rospack.get_manifest(pkg)
[gazebo-2] killing on exit
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 171, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 215, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python2.7/dist-packages/rospkg/manifest.py", line 410, in parse_manifest_file
    from rosdep2.rospack import init_rospack_interface, is_ros_package, is_system_dependency, is_view_empty
  File "/usr/lib/python2.7/dist-packages/rosdep2/__init__.py", line 45, in <module>
    from .lookup import RosdepDefinition, RosdepView, RosdepLookup, \
  File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 44, in <module>
    from .sources_list import SourcesListLoader
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 42, in <module>
    from .gbpdistro_support import get_gbprepo_as_rosdep_data, download_gbpdistro_as_rosdep_data
  File "/usr/lib/python2.7/dist-packages/rosdep2/gbpdistro_support.py", line 14, in <module>
    from .platforms.debian import APT_INSTALLER
  File "/usr/lib/python2.7/dist-packages/rosdep2/platforms/debian.py", line 46, in <module>
    from .pip import PIP_INSTALLER
  File "/usr/lib/python2.7/dist-packages/rosdep2/platforms/pip.py", line 33, in <module>
    import pkg_resources
  File "/home/dlvirmac/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/dlvirmac/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/dlvirmac/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/dlvirmac/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/home/dlvirmac/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/home/dlvirmac/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/dlvirmac/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2065, in find_on_path
    for dist in factory(fullpath):
  File "/home/dlvirmac/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2127, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
KeyboardInterrupt
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
![error 1 and 2](https://github.com/ethz-asl/mav_active_3d_planning/assets/130729781/fe316a9c-4129-4afd-92f5-63dd9f2fba2e)
![error 3 and 4](https://github.com/ethz-asl/mav_active_3d_planning/assets/130729781/dcbe71ed-04d5-45c5-9df5-5b5720e06edc)

**Comment by Schmluk** [comment]
Hi @zcc0514 

Have you installed all dependencies, built them, and source your workspace? It looks like ros can not find your nodes.

**Comment by zcc0514** [comment]
Then I would like to ask, how to solve my problem? Because I'm a novice, I'm new to ros. I hope you can give me some good suggestions, and thank you sincerely for your reply again!

**Comment by Schmluk** [comment]
Have you tried `source ~/catkinw_ws/devel/.bashrc`?

There's many great ROS tutorials available online (e.g. http://wiki.ros.org/ROS/Tutorials). I'd suggest familiarizing yourself with ROS and let us know if your errors persist!
